import json

import pandas as pd
import csv

def processTextItem(l,textItemID):
    if(len(l) > 0):
        r = l[0]
        final_list.append(textItemID+":"+r)

with open('/Users/avneet/Desktop/CS249/PROJECT/evaluation-text.json') as data_file:
    test_ann_textItems = json.load(data_file)

test_ann_textItems = pd.DataFrame(list(test_ann_textItems['TextItem'].items()))
test_ann_textItems.columns = ['id', 'text']


final_list = []
##Processing output file generated by Mallet and Stanford NER
test_labels = pd.read_csv('/Users/avneet/Desktop/CS249/M/Test_output',sep=' ',skip_blank_lines=False,header = None)
test_labels.columns = ['token', 'label']

text_index = 0
index_str="";
seperator ="-"
l = []
i = 0
while(i < len(test_labels['label'])):
    label = str(test_labels['label'][i])
    #print(label+":"+str(i)+ " "+str(test_labels['token'][i])+" "+str(text_index))
    if(label == 'nan'):
        processTextItem(l, test_ann_textItems['id'][i])
        text_index = 0
        l.clear()
        i = i+1
    elif(label == 'prod'):
        start_index = text_index
        end_index = text_index
        while(label == 'prod'):
            end_index+=1
            text_index+=1
            i = i+1
            label = str(test_labels['label'][i])
        l.append(str(start_index)+seperator+str(end_index-1))
    elif(label == 'O'):
        text_index +=1
        i = i+1
processTextItem(l, test_ann_textItems['id'][i-1])

print(final_list)

with open("output.csv", "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    for val in final_list:
        writer.writerow([val])
